# Generated by Django 4.2.2 on 2023-06-30 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edge', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='organizer',
            field=models.CharField(default='Unknown', max_length=100),
        ),
        migrations.AddField(
            model_name='event',
            name='ticket_price',
            field=models.DecimalField(decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='venue_address',
            field=models.CharField(default='Adress not yet listed', max_length=100),
        ),
        migrations.AddField(
            model_name='event',
            name='venue_name',
            field=models.CharField(default='Venue name not yet listed', max_length=100),
        ),
    ]
