# Generated by Django 4.2.2 on 2023-07-01 07:06

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('edge', '0003_user_user_type_alter_booking_quantity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='image',
            field=models.ImageField(upload_to='static/event_images/%Y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='contact_number',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None),
        ),
    ]
