# Generated by Django 4.2.2 on 2023-07-01 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edge', '0004_alter_event_image_alter_userprofile_contact_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='ticket_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
    ]
