# Generated by Django 4.2.2 on 2023-07-01 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edge', '0008_remove_event_organizer_id_alter_event_organizer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='image',
            field=models.ImageField(upload_to='event_images/%Y/%m/%d'),
        ),
    ]
