# Generated by Django 4.2.2 on 2023-07-06 23:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('edge', '0016_alter_booking_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
