# Generated by Django 4.2.2 on 2023-07-08 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edge', '0017_delete_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=6),
        ),
        migrations.AddField(
            model_name='booking',
            name='total_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
    ]
